# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic',
            field=models.FileField(upload_to='static/upload'),
        ),
    ]
