# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160616_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic',
            field=models.CharField(max_length=125),
        ),
    ]
